create table if not exists public."Errores_App" (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  usuario_id uuid null,
  email text null,
  modulo text not null,
  accion text not null,
  mensaje text not null,
  stack text null,
  contexto_json jsonb not null default '{}'::jsonb
);

create index if not exists errores_app_fecha_idx
  on public."Errores_App" (fecha desc);

create index if not exists errores_app_usuario_idx
  on public."Errores_App" (usuario_id, fecha desc);

alter table public."Errores_App" enable row level security;

create policy if not exists "errores_app_insert_propios"
  on public."Errores_App"
  for insert
  to authenticated
  with check (
    usuario_id is null or auth.uid() = usuario_id
  );

create policy if not exists "errores_app_select_propios"
  on public."Errores_App"
  for select
  to authenticated
  using (
    usuario_id is null or auth.uid() = usuario_id
  );
